theme: jekyll-theme-minimal
title: FlexBr.com
logo: https://avatars0.githubusercontent.com/u/14129483?s=240&v=4
description: Ol√°, eu sou Ricardo Ramires.<br/> Bem vindo ao meu site pessoal!
show_downloads: false
navigation:
  - title: Home
    url: /
  - title: Artigos
    url: /articles
  - title: Setup
    url: setup
